services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - "127.0.0.1:8670:8000"  # Bind to localhost only
    command: start --log warn --user root --pass root rocksdb:///mydata/database.db
    env_file:
      - stack.env
    volumes:
      - surreal_data:/mydata
    restart: always
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "0.5"

  open_notebook:
    image: lfnovo/open_notebook:v1-latest
    ports:
      - "8502:8502"  # Web UI
      - "5055:5055"  # API (required!)
    volumes:
      - notebook_data:/app/data
    env_file:
      - stack.env
    depends_on:
      - surrealdb
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
  
volumes:
  notebook_data:
  surreal_data: